#!/usr/bin/env python
# -*- coding: utf-8 -*-

ignore_me = ["",
             u"Oil: Production *",
             u"* Includes crude oil, shale oil, oil sands and NGLs ( the liquid content of natural gas where this is recovered separately).",
             u"Excludes liquid fuels from other sources such as biomass and coal derivatives.",
             u"^ Less than 0.05.",
             u"Notes: Annual changes and shares of total are calculated using thousand barrels daily figures.",
             u"w Less than 0.05%.",
             u"Excludes Former Soviet Union.",
             u"# Excludes Estonia, Latvia and Lithuania prior to 1985 and Slovenia prior to 1991.",
             u"Notes: Annual changes and shares of total are calculated using million tonnes per annum figures.",
             u"* Includes crude oil, tight oil, oil sands and NGLs (the liquid content of natural gas where this is recovered separately). Excludes liquid fuels from other sources such as biomass and derivatives of coal and natural gas.",
             u"coal and natural gas.",
             u"n/a not available.",
             u"Note: Annual changes and shares of total are calculated using million tonnes per annum figures.",
             #
             u"Notes: Annual changes and shares of total are calculated using million tonnes oil equivalent figures.",
             u"Growth rates are adjusted for leap years.",
             u"Carbon Dioxide Emissions",
             u"Notes: The carbon emissions above reflect only those through consumption of oil, gas and coal for combustion related activities, and are based on",
             u"Notes: Annual changes and shares of total are calculated using million tonnes figures.",
             u"Growth rates are adjusted for growth rates",
             u"Annual changes and shares of total are calculated using billion cubic metres figures.",
             u"Growth rates are adjusted for leap years.",
             u"Annual changes and shares of total are calculated using billion cubic feet per day figures.",
             u"Notes: Annual changes and shares of total are calculated using million tonnes figures.",
             u"Growth rates are adjusted for leap years.",
             u"Notes: Annual changes and shares of total are calculated using million tonnes oil equivalent figures.",
             u"Growth rates are adjusted for growth rates",
             u"Natural Gas: Proved reserves",
             u"Notes: Total proved reserves of natural gas - Generally taken to be those quantities that geological and engineering information indicates with reasonable certainty",
             u"can be recovered in the future from known reservoirs under existing economic and operating conditions. The data series for natural gas does not necessarily",
             u"Reserves-to-production (R/P) ratio - If the reserves remaining at the end of any year are divided by the production in that year, the result is the length of time",
             u"that those remaining reserves would last if production were to continue at that rate.",
             u"Source of data - The estimates in this table have been compiled using a combination of primary official sources and third-party data from Cedigaz and the OPEC Secretariat.",
             u"Annual changes and share of total are calculated using trillion cubic metres.",
             u"Oil: Proved reserves in thousand million barrels",
             u"Canadian Oil Sands: Total",
             u"of which: Under active development",
             u"Venezuela: Orinoco Belt",
             u"# Excludes Estonia, Latvia and Lithuania prior to 1996 and Slovenia prior to 1990.",
             u" 'Remaining established reserves', less reserves 'under active development'.",
             u"Notes: Total proved reserves of oil - Generally taken to be those quantities that geological and engineering information indicates with reasonable certainty",
             u"can be recovered in the future from known reservoirs under existing economic and operating conditions. The data series for total proved oil does not necessarily",
             u"meet the definitions, guidelines and practices used for determining proved reserves at company level, for instance as published by the US Securities and Exchange Commission,",
             u"nor does it necessarily represent BP’s view of proved reserves by country.",
             u"Reserves-to-production (R/P) ratio - If the reserves remaining at the end of any year are divided by the production in that year, the result is the length of time that those remaining reserves would last if",
             u"production were to continue at that rate.",
             u"Source of data - The estimates in this table have been compiled using a combination of primary official sources, third-party data from the OPEC Secretariat, World Oil, Oil &",
             u"Gas Journal and an independent estimates of Russian reserves based on official data and Chinese reserves based on information in the public domain.",
             u"Canadian oil sands 'under active development' are an official estimate. Venezuelan Orinoco Belt reserves are based on the OPEC Secretariat and government announcements.",
             u"Reserves include gas condensate and natural gas liquids (NGLs) as well as crude oil.",
             u"Annual changes and shares of total are calculated using thousand million barrels figures.",
             u"Oil: Consumption *",
             u"* Includes crude oil, shale oil, oil sands and NGLs (the liquid content of natural gas where this is recovered separately).",
             u"* Inland demand plus international aviation and marine bunkers and refinery fuel and loss.  Consumption of fuel ethanol and biodiesel is also included.",
             u"* Includes crude oil, tight oil, oil sands and NGLs (the liquid content of natural gas where this is recovered separately). Excludes liquid fuels from other sources such as biomass and derivatives of",
             u"* Inland demand plus international aviation and marine bunkers and refinery fuel and loss. Consumption of biogasoline (such as ethanol), biodiesel and derivatives of coal and natural gas are also included.",
             u"Notes: Differences between these world consumption figures and world production statistics are accounted for by stock changes, consumption of non-petroleum additives",
             u"* Excludes gas flared or recycled. Includes natural gas produced for Gas-to-Liquids transformation.",
             u"Notes:  As far as possible, the data above represent standard cubic metres (measured at 15ºC and 1013 mbar); as they are derived directly from tonnes of oil equivalent using an average conversion factor,",
             u"Notes: Annual changes and shares of total are calculated using million tonnes of oil equivalent figures.",
             u"Notes: As the data above are derived from tonnes oil equivalent using average conversion factors, they do not necessarily equate with gas volumes expressed in specific national terms.",
             u"Annual changes and shares of total are calculated using million tonnes of oil equivalent figures.",
             u"*Excludes gas flared or recycled. Includes natural gas produced for Gas-to-Liquids transformation.",
             u"Natural Gas: Consumption*",
             u"* Excludes natural gas converted to liquid fuels but includes derivatives of coal as well as natural gas consumed in Gas-to-Liquids transformation.",
             u"Notes: As far as possible, the data above represent standard cubic metres (measured at 15oC and 1013 mbar); as they are derived directly from tonnes",
             u"Notes: The difference between these world consumption figures and the world production statistics is due to variations in stocks at storage facilities",
             u"* Commercial solid fuels only, i.e. bituminous coal and anthracite (hard coal), and lignite and brown (sub-bituminous) coal, and other solid commercial solid fuels. Includes coal produced for Coal-to-Liquids and Coal-to-Gas transformations.",
             u"^ Less than 0.5.",
             u"Notes:  Annual changes and shares of total are calculated using million tonnes per annum figures.",
             u"Differences between these world consumption figures and world production statistics are accounted for by stock changes, consumption of non-petroleum additives",
             u"and substitute fuels, and unavoidable disparities in the definition, measurement or conversion of oil supply and demand data.",
             u"Note: Differences between these world consumption figures and world production statistics are accounted for by stock changes, consumption of non-petroleum additives",
             #
             u"Natural Gas: Production *",
             u"* Excluding gas flared or recyled.",
             u"Notes:  As far as possible, the data above represent standard cubic metres measured at 15oC and 1013 millibar (mbar); as they are derived directly from tonnes",
             u"Note: Annual changes and shares of total are calculated using million tonnes of oil equivalent figures.",
             u"* Commercial solid fuels only, i.e. bituminous coal and anthracite (hard coal), and lignite and brown (sub-bituminous) coal and other commercial solid fuels. Includes coal produced for Coal-to-Liquids and Coal-to-Gas transformations.",
             u"* Commercial solid fuels only, i.e. bituminous coal and anthracite (hard coal), and lignite and brown (sub-bituminous) coal. Excludes coal converted to liquid or gaseous fuels, but includes coal consumed in transformation processes.",
             u"""Note:  Differences between these world consumption figures and the world production statistics are accounted for by stock changes, and unavoidable disparities in the definition, measurement
or conversion of coal supply and demand data.""",
             u"Note: Annual changes and shares of total are calculated using million tonnes of oil equivalent figures.",
             u"* Based on gross generation and not accounting for cross-border electricity supply. Converted on the basis of thermal equivalence assuming 38% conversion efficiency in a modern thermal power station.",
             u"Note: Annual changes and shares of total are calculated using million tonnes of oil equivalent figures.",
             u"Renewables: Consumption *",
             u"* Based on gross generation from renewable sources including wind,geothermal,solar,biomass and waste, and not accounting for cross-border electricity supply.",
             u"Renewables: Consumption *",
             u"* Based on gross generation from renewable sources including wind,geothermal,solar,biomass and waste, and not accounting for cross-border electricity supply.",
             u"* Based on gross generation and not accounting for cross-border electricity supply. Converted on the",
             u"basis of thermal equivalence assuming 38% conversion efficiency in a modern thermal power station.",
             u"of oil equivalent using an average conversion factor, they do not necessarily equate with gas volumes expressed in specific national terms.",
             u"Notes: Annual changes and shares of total are calculated in million tonnes of oil equilevent figures.",
             u"As the data above are derived from tonnes oil equivalent using average conversion factors,",
             u"they do not necessarily equate with gas volumes expressed in specific national terms.",
             u"w Less than 0.05%",
             #
             u"Natural Gas: Consumption",
             u"Oil: Production*",
             u"CIS",
             u"* Includes crude oil, shale oil, oil sands and NGLs (natural gas liquids - the liquid content of natural gas where this is recovered separately).",
             u"Excludes liquid fuels from other sources such as biomass and derivatives of coal and natural gas.",
             u"# Excludes Estonia, Latvia and Lithuania prior to 1985 and Slovenia prior to 1990.",
             u"Notes: Annual changes and shares of total are calculated using million tonnes of oil equilevent figures.",
             u"As far as possible, the data above represent standard cubic metres (measured at 15oC and 1013 mbar); as they are derived directly from tonnes",
             #
             u"Natural Gas: Consumption",
             u"Oil: Consumption*",
             #u"Billion cubic feet",
             u"Natural Gas: Production*",
             u"Note: As far as possible, the data above represent standard cubic metres (measured at 15oC and 1013 mbar); as they are derived directly from tonnes",
             u"The difference between these world consumption figures and the world production statistics is due to variations in stocks at storage facilities",
             u"and liquefaction plants, together with unavoidable disparities in the definition, measurement or conversion of gas supply and demand data.",
             u"Note: The difference between these world consumption figures and the world production statistics is due to variations in stocks at storage facilities",
             #
             u"Coal: Production *",
             u"* Commercial solid fuels only, i.e. bituminous coal and anthracite (hard coal), and lignite and brown (sub-bituminous) coal.",
             u"Notes: Annual changes and shares of total are based on data expressed in tonnes oil equivalent.",
             #
             u"Coal: Consumption *",
             #
             u"Nuclear: Consumption *",
             u"* Based on gross generation and not accounting for cross-border electricity supply.",
             u"Converted on the basis of thermal equivalence assuming 38% conversion efficiency in a modern thermal power station.",
             #
             u"Hydroelectricity: Consumption *",
             u"* Based on gross primary hydroelectric generation and not accounting for cross-border electricity supply.",
             u"* Based on gross primary hydroelectric generation and not accounting for cross-border electricity supply.  Converted on the basis of thermal equivalence assuming 38%",
             u"conversion efficiency in a modern thermal power station.",
             #
             u"Other renewables: Consumption *",
             u"* Based on gross generation from renewable sources including wind,geothermal,solar,biomass and waste, and not accounting for cross border electricity supply.",
             u"Converted on the basis of thermal equivalence assuming 38% conversion efficiency in a modern thermal power station.",
             u"^ Less than 0.05",
             u"♦ Less than 0.05%",  # TODO:  This string doesn't match
             u"# Excludes Slovenia prior to 1991",
             #
             u"Renewables: Consumption - Solar *",
             u"Other North America",
             u"♦ Less than 0.05%.",  # TODO:  This string doesn't match
             #
             u"Renewables: Consumption - Wind *",
             u"Coal: Production*",
             u"* Commercial solid fuels only, i.e. bituminous coal and anthracite (hard coal), and lignite and brown (sub-bituminous) coal, and other commercial solid fuels. Includes coal produced for Coal-to-Liquids and Coal-to-Gas transformations.",
             u"Renewables: Consumption  - Solar*",
             u"Renewables: Consumption  - Wind*",
             u"Nuclear: Consumption*",
             u"Coal: Consumption*",
             u"* Commercial solid fuels only, i.e. bituminous coal and anthracite (hard coal), and lignite and brown (sub-bituminous) coal, and other commercial solid fuels.",
             u"Excludes coal converted to liquid or gaseous fuels, but includes coal consumed in transformation processes.",
             u"Hydroelectricity: Consumption*",
             u"* Based on gross primary hydroelectric generation and not accounting for cross-border electricity supply. Converted on the",
             u"Renewables: Consumption*",
             u"* Based on gross generation from renewable sources including wind, geothermal, solar, biomass and waste, and not accounting for cross-border electricity supply.",
             u"Renewables: Consumption - Solar*",
             u"Renewables: Consumption - Wind*",
             u"Natural Gas: Consumption in billion cubic metres*",
             u"Renewables: Consumption - Geothermal, Biomass and Other*",
             u"# Excludes Estonia, Latvia and Lithuania prior to 1985 and Croatia and Slovenia prior to 1990.",
             u"Electricity Generation*",
             u"Renewables: Generation*",
             u"Gas Journal and an independent estimates of Russian reserves based on official data and Chinese reserves based on official data and information in the public domain.",
             u"Note: Annual changes and shares of total are calculated using thousand barrels daily figures.",
             u"Nuclear: Generation*",
             u"of oil equivalent using an average conversion factor and have been standardized using a Gross Calorific Value (GCV) of 40 MJ/m3,",
             u"Renewables: Generation- Solar*",
             u"Renewables: Generation- Geothermal, Biomass and Other*",
             u"n/a not applicable.",
             u"Hydroelectricity: Generation*",
             u"Renewables: Generation- Wind*",
             u"As far as possible, the data above represents standard cubic metres (measured at 15ºC and 1013 mbar) and has been standardized using a Gross Calorific Value (GCV) of 40 MJ/m3.",
             u"USSR includes Georgia and the Baltic States.",
                              u"#  Excludes Estonia, Latvia and Lithuania prior to 1985 and Croatia and Slovenia prior to 1990.",
                              u"Notes: Annual changes and share of total are calculated using million tonnes oil equivalent figures.",
                              u"Notes: Annual changes and shares of total are calculated using terawatt-hours figures.",
                              u"'Default CO2 Emissions Factors for Combustion' listed by the IPCC in its Guidelines for National Greenhouse Gas Inventories (2006).",
                              u"This does not allow for any carbon that is sequestered, for other sources of carbon emissions, or for emissions of other greenhouse gases.",
                              u"Our data is therefore not comparable to official national emissions data.",
                              u"* Based on gross output.",
                              u"# Excludes Croatia and Slovenia prior to 1990.",
                              u"Notes: Annual changes and share of total are calculated using terawatt-hours figures.",
                              u"Annual changes and shares of total are calculated using thousand barrels daily figures.",
                              u"Annual changes and share of total are calculated using million tonnes oil equivalent figures.",
                 u"Notes:  Differences between these consumption figures and the world production statistics are accounted for by stock changes, and unadvoidable disparities in the definition, measurement or conversion of coal supply and demand data.",
                 u"Annual changes and shares of total are calculated using million tonnes figures.",

             ]
