title_to_filename = {
        #'Contents',
        #'Primary Energy Consumption',
        #'Primary Energy - Cons by fuel',
        #'Oil - Proved reserves',

        'Oil - Proved reserves history' : 'oil_proved_reserves_gb',
        'Oil Production - Barrels' : 'oil_production_bbl',
        'Oil Production - Tonnes' : 'oil_production_mtoe',
        'Oil Consumption - Barrels': 'oil_consumption_bbl',
        'Oil Consumption - Tonnes': 'oil_consumption_mtoe',

        #'Oil - Regional Consumption ',
        #'Oil - Spot crude prices',
        #'Oil - Crude prices since 1861',
        #'Oil - Refinery throughput',
        #'Oil - Refinery capacities',
        #'Oil - Regional refining margins',
        #'Oil - Trade movements',
        #'Oil - Inter-area movements ',
        #'Oil - Trade 2015 - 2016',
        #'Gas - Proved reserves',

        'Gas - Proved reserves history ' : 'gas_proved_reserves_trillion_cubic_metres',
        'Gas Production - Bcm' : 'gas_production_m3',
        'Gas Production - Bcf' : 'gas_production_ft3',
        'Gas Production - Mtoe' : 'gas_production_mtoe',
        'Gas Consumption - Bcm' : 'gas_consumption_m3',
        'Gas Consumption - Bcf' : 'gas_consumption_ft3',
        'Gas Consumption - Mtoe' : 'gas_consumption_mtoe',

        # 'Gas - Trade - pipeline',
        # 'Gas - Trade movements LNG',
        # 'Gas - Trade 2015-2016',
        # 'Gas - Prices ',
        # 'Coal - Reserves',
        # 'Coal - Prices',

        'Coal Production - Tonnes' : 'coal_production_ton',
        'Coal Production - Mtoe' : 'coal_production_mtoe',
        'Coal Consumption - Mtoe' : 'coal_consumption_mtoe',
        'Nuclear Consumption - TWh' : 'nuclear_consumption_twh',
        'Nuclear Consumption - Mtoe' : 'nuclear_consumption_mtoe',
        'Hydro Consumption - TWh' : 'hydro_consumption_twh',
        'Hydro Consumption - Mtoe': 'hydro_consumption_mtoe',
        'Other renewables - TWh' : 'renewables_consumption_twh',
        'Other renewables - Mtoe' : 'renewables_consumption_mtoe',
        'Solar Consumption - TWh' : 'solar_consumption_twh',
        'Solar Consumption - Mtoe': 'solar_consumption_mtoe',
        'Wind Consumption - TWh ': 'wind_consumption_twh',
        'Wind Consumption - Mtoe': 'wind_consumption_mtoe',
        'Geo Biomass Other - TWh' : 'geo_biomass_other_twh',
        'Geo Biomass Other - Mtoe' : 'geo_biomass_other_mtoe',

        # 'Biofuels Production - Kboed',
        # 'Biofuels Production - Ktoe',

        'Electricity Generation ' : 'electricity_generation_twh',
        'Carbon Dioxide Emissions' : 'co2_emissions_mt',

        # 'Geothermal capacity',
        # 'Solar capacity',
        # 'Wind capacity',
        # 'Approximate conversion factors',
        # 'Definitions'
    }
